CREATE TABLE case_info
(
    data[0].allfields.after_data.SEND_TIME.value varchar as SEND_TIME,
    data[0].allfields.after_data.PHONE_NUMBER.value varchar as PHONE_NUMBER,
    data[0].allfields.after_data.AREA_CODE.value varchar as AREA_CODE,
    data[0].allfields.after_data.CASE_TITLE.value varchar as CASE_TITLE,
    data[0].allfields.after_data.CASE_DATE.value timestamp as CASE_DATE,
    data[0].allfields.after_data.FINISH_TIME.value varchar as FINISH_TIME,
    data[0].allfields.after_data.SUBJECT_RESULT_SATIFY.value varchar as SUBJECT_RESULT_SATIFY,
    data[0].allfields.after_data.CASE_CONTENT.value varchar as CASE_CONTENT,
    data[0].allfields.after_data.FDBACK.value varchar as FDBACK,
    data[0].allfields.after_data.RQSTSOURCECHILD.value varchar as RQSTSOURCECHILD,
    data[0].allfields.after_data.TBACKTIME_BF.value varchar as TBACKTIME_BF,
    data[0].allfields.after_data.EVENT_DATE.value timestamp as EVENT_DATE,
    data[0].allfields.after_data.ISKAOHE.value varchar as ISKAOHE,
    data[0].allfields.after_data.END_DEPT.value varchar as END_DEPT,
    data[0].allfields.after_data.CONCACT_TIME.value varchar as CONCACT_TIME,
    data[0].allfields.after_data.FDBACKTIME.value varchar as FDBACKTIME,
    data[0].allfields.after_data.CASE_EX_ACCORD.value varchar as CASE_EX_ACCORD,
    data[0].allfields.after_data.RELATE_SERIAL.value varchar as RELATE_SERIAL,
    data[0].allfields.after_data.CASE_ADDRESS.value varchar as CASE_ADDRESS,
    data[0].allfields.after_data.CASE_MARK.value varchar as CASE_MARK,
    data[0].allfields.after_data.COMPLAINT_DETAIL.value varchar as COMPLAINT_DETAIL,
    data[0].allfields.after_data.SIGN_TIME.value varchar as SIGN_TIME,
    data[0].allfields.after_data..value varchar as APPLICANT_SEX,
    data[0].allfields.after_data..value varchar as CASE_ACCORD,
    data[0].allfields.after_data..value varchar as APPLICANT_TYPE,
    data[0].allfields.after_data..value varchar as case_accord_text,
    data[0].allfields.after_data..value varchar as CASE_EMOTION,
    data[0].allfields.after_data..value varchar as CASE_GOAL,
    data[0].allfields.after_data..value varchar as CERTIFICATE_TYPE,
    data[0].allfields.after_data..value varchar as CASE_SOURCE,
    data[0].allfields.after_data..value varchar as FINISH_NOTE,
    data[0].allfields.after_data..value varchar as CASE_REGISTER,
    data[0].allfields.after_data..value varchar as ENTERPRISE_NAME,
    data[0].allfields.after_data..value varchar as CASE_PROCESS_TYPE,
    data[0].allfields.after_data..value varchar as ROWGUID,
    data[0].allfields.after_data.VISIT_TYPE.value varchar as VISIT_TYPE,
    data[0].allfields.after_data.RELATION_DEPTSCODE.value varchar as RELATION_DEPTSCODE,
    data[0].allfields.after_data.OPERATEDATE.value timestamp as OPERATEDATE,
    data[0].allfields.after_data.FINISH_TYPE.value varchar as FINISH_TYPE,
    data[0].allfields.after_data.THEME_SERIAL.value varchar as THEME_SERIAL,
    data[0].allfields.after_data.CASE_ISURGENT.value varchar as CASE_ISURGENT,
    data[0].allfields.after_data.TFDBACKTIME_BF.value varchar as TFDBACKTIME_BF,
    data[0].allfields.after_data.CASE_ISVISIT.value varchar as CASE_ISVISIT,
    data[0].allfields.after_data.OPERATEDATE1.value varchar as OPERATEDATE1,
    data[0].allfields.after_data.CASE_AREA_CODE.value varchar as CASE_AREA_CODE,
    data[0].allfields.after_data.TSIGNTIME_BF.value varchar as TSIGNTIME_BF,
    data[0].allfields.after_data.VISIT_REMARK.value varchar as VISIT_REMARK,
    data[0].allfields.after_data.RELATION_DEPTS.value varchar as RELATION_DEPTS,
    data[0].allfields.after_data.new_case_accord.value varchar as new_case_accord,
    data[0].allfields.after_data.flag.value varchar as flag,
    data[0].allfields.after_data.END_NAME.value varchar as END_NAME,
    data[0].allfields.after_data.CASE_LNGLAT.value varchar as CASE_LNGLAT,
    data[0].allfields.after_data.CASE_ISPUBLIC.value varchar as CASE_ISPUBLIC,
    data[0].allfields.after_data.CASE_SERIAL_TURN.value varchar as CASE_SERIAL_TURN,
    data[0].allfields.after_data.CASE_SOURCE_DETAIL.value varchar as CASE_SOURCE_DETAIL,
    data[0].allfields.after_data.CASE_TYPE.value varchar as CASE_TYPE,
    data[0].allfields.after_data.CASE_HISTORYNUM.value decimal as CASE_HISTORYNUM,
    data[0].allfields.after_data.REQUENCY.value decimal as REQUENCY,
    data[0].allfields.after_data.APPLICANT_AGE.value decimal as APPLICANT_AGE,
    data[0].allfields.after_data.CASE_REGISTERNO.value varchar as CASE_REGISTERNO,
    data[0].allfields.after_data.flagguid.value varchar as flagguid,
    data[0].allfields.after_data.HANDLETIME_LONG.value decimal as HANDLETIME_LONG,
    data[0].allfields.after_data.CASE_SERIAL.value varchar as CASE_SERIAL,
    data[0].allfields.after_data.APPLICANT_NAME.value varchar as APPLICANT_NAME,
    data[0].allfields.after_data.APPLICANT_ID.value varchar as APPLICANT_ID,
    data[0].allfields.after_data.RELATION_POLICE_OFFICER.value varchar as RELATION_POLICE_OFFICER,
    data[0].allfields.after_data.date_id.value bigint as date_id
)
    WITH (type = 'kafka',groupId = 'group_case_info',bootstrapServers = '192.168.204.117:9092',zookeeperQuorum = '192.168.204.117:2181',offsetReset = 'earliest',timezone = 'Asia/Shanghai',topic = 'cs_dorisdb');

CREATE TABLE target
(
    ROWGUID                 varchar,
    CASE_SERIAL             varchar,
    CASE_TITLE              varchar,
    CASE_REGISTER           varchar,
    CASE_REGISTERNO         varchar,
    CASE_DATE               timestamp,
    CASE_SOURCE             varchar,
    CASE_SOURCE_DETAIL      varchar,
    PHONE_NUMBER            varchar,
    APPLICANT_NAME          varchar,
    APPLICANT_SEX           varchar,
    APPLICANT_AGE           decimal,
    APPLICANT_ID            varchar,
    CASE_TYPE               varchar,
    CASE_ACCORD             varchar,
    CASE_CONTENT            varchar,
    CASE_PROCESS_TYPE       varchar,
    CASE_ISPUBLIC           varchar,
    CASE_ISVISIT            varchar,
    CASE_ISURGENT           varchar,
    CASE_MARK               varchar,
    AREA_CODE               varchar,
    CASE_SERIAL_TURN        varchar,
    TSIGNTIME_BF            datetime,
    TFDBACKTIME_BF          datetime,
    TBACKTIME_BF            datetime,
    RELATE_SERIAL           varchar,
    CASE_AREA_CODE          varchar,
    CASE_LNGLAT             varchar,
    CASE_EMOTION            varchar,
    CASE_EX_ACCORD          varchar,
    CASE_ADDRESS            varchar,
    EVENT_DATE              datetime,
    CASE_GOAL               varchar,
    CERTIFICATE_TYPE        varchar,
    CASE_HISTORYNUM         decimal,
    THEME_SERIAL            varchar,
    OPERATEDATE             datetime,
    REQUENCY                decimal,
    OPERATEDATE1            datetime,
    SUBJECT_RESULT_SATIFY   varchar,
    VISIT_REMARK            varchar,
    VISIT_TYPE              varchar,
    END_DEPT                varchar,
    END_NAME                varchar,
    CONCACT_TIME            datetime,
    FINISH_TIME             datetime,
    FINISH_NOTE             varchar,
    FINISH_TYPE             varchar,
    HANDLETIME_LONG         decimal,
    SIGN_TIME               datetime,
    FDBACKTIME              datetime,
    SEND_TIME               datetime,
    FDBACK                  varchar,
    flag                    varchar,
    flagguid                varchar,
    ISKAOHE                 varchar,
    RQSTSOURCECHILD         varchar,
    COMPLAINT_DETAIL        varchar,
    APPLICANT_TYPE          varchar,
    ENTERPRISE_NAME         varchar,
    RELATION_DEPTSCODE      varchar,
    RELATION_DEPTS          varchar,
    RELATION_POLICE_OFFICER varchar,
    case_accord_text        varchar,
    new_case_accord         varchar,
    date_id                 bigint
)
    WITH (type = 'dorisdb',url = 'jdbc:mysql://192.168.186.66:9030/tmldb_source?rewriteBatchedStatements=true',jdbcUrl = 'jdbc:mysql://192.168.186.66:9030/tmldb_source?rewriteBatchedStatements=true',loadUrl = '192.168.186.66:8030',databaseName = 'tmldb_source',tableName = 'O_ST_XTGLB_zhenjiang_case_info',userName = 'test_user',password = '11111',sink.properties.strip_outer_array = 'true',parallelism = '1',sink.buffer-flush.interval-ms = '1000',sink.properties.format = 'json',sink.properties.column_separator = '\\x01',sink.properties.row_delimiter = '\\x02',fastCheck = 'false');


insert into target
SELECT ROWGUID,
       CASE_SERIAL,
       CASE_TITLE,
       CASE_REGISTER,
       CASE_REGISTERNO,
       CASE_DATE,
       CASE_SOURCE,
       CASE_SOURCE_DETAIL,
       PHONE_NUMBER,
       APPLICANT_NAME,
       APPLICANT_SEX,
       APPLICANT_AGE,
       APPLICANT_ID,
       CASE_TYPE,
       CASE_ACCORD,
       CASE_CONTENT,
       CASE_PROCESS_TYPE,
       CASE_ISPUBLIC,
       CASE_ISVISIT,
       CASE_ISURGENT,
       CASE_MARK,
       AREA_CODE,
       CASE_SERIAL_TURN,
       TO_TIMESTAMP(TSIGNTIME_BF)   as TSIGNTIME_BF,
       TO_TIMESTAMP(TFDBACKTIME_BF) as TFDBACKTIME_BF,
       TO_TIMESTAMP(TBACKTIME_BF)   as TBACKTIME_BF,
       RELATE_SERIAL,
       CASE_AREA_CODE,
       CASE_LNGLAT,
       CASE_EMOTION,
       CASE_EX_ACCORD,
       CASE_ADDRESS,
       EVENT_DATE,
       CASE_GOAL,
       CERTIFICATE_TYPE,
       CASE_HISTORYNUM,
       THEME_SERIAL,
       OPERATEDATE,
       REQUENCY,
       TO_TIMESTAMP(OPERATEDATE1)   as OPERATEDATE1,
       SUBJECT_RESULT_SATIFY,
       VISIT_REMARK,
       VISIT_TYPE,
       END_DEPT,
       END_NAME,
       TO_TIMESTAMP(CONCACT_TIME)   as CONCACT_TIME,
       TO_TIMESTAMP(FINISH_TIME)    as FINISH_TIME,
       FINISH_NOTE,
       FINISH_TYPE,
       HANDLETIME_LONG,
       TO_TIMESTAMP(SIGN_TIME)      as SIGN_TIME,
       TO_TIMESTAMP(FDBACKTIME)     as FDBACKTIME,
       TO_TIMESTAMP(SEND_TIME)      as SEND_TIME,
       FDBACK,
       flag,
       flagguid,
       ISKAOHE,
       RQSTSOURCECHILD,
       COMPLAINT_DETAIL,
       APPLICANT_TYPE,
       ENTERPRISE_NAME,
       RELATION_DEPTSCODE,
       RELATION_DEPTS,
       RELATION_POLICE_OFFICER,
       case_accord_text,
       new_case_accord,
       date_id
from case_info